# Generated by Django 3.2.3 on 2021-05-16 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id_subject', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=50)),
                ('grade', models.FloatField(default=0)),
                ('date_created', models.DateTimeField()),
                ('date_finished', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeActivity',
            fields=[
                ('id_activity', models.AutoField(primary_key=True, serialize=False)),
                ('type_activity', models.CharField(choices=[('Pa', 'Parcial'), ('Q', 'Quicez'), ('T', 'Taller'), ('E', 'Expocision'), ('Pr', 'Proyecto')], default='T', help_text='Tipo de actividad', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id_activity', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('state', models.BooleanField(default=False)),
                ('grade', models.FloatField(default=0)),
                ('date_created', models.DateTimeField()),
                ('date_finished', models.DateTimeField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('type_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.typeactivity')),
            ],
        ),
    ]
